"""create_schema

Revision ID: 02b2f7a1bf6e
Revises:
Create Date: 2024-08-07 14:55:54.029555

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "02b2f7a1bf6e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
