"""create triggers

Revision ID: 7e654e9b6e36
Revises: 5c20420a85c8
Create Date: 2024-08-07 16:07:56.245728

"""
from typing import Sequence, Union

from alembic import op
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = "7e654e9b6e36"
down_revision: Union[str, None] = "5c20420a85c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    iag_divide_operations_update_divide_operations_modtime = PGTrigger(
        schema="iag",
        signature="update_divide_operations_modtime",
        on_entity="iag.divide_operations",
        is_constraint=False,
        definition="BEFORE UPDATE ON divide_operations\n    FOR EACH ROW EXECUTE FUNCTION iag.update_updated_at_column()",
    )
    op.create_entity(iag_divide_operations_update_divide_operations_modtime)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    iag_divide_operations_update_divide_operations_modtime = PGTrigger(
        schema="iag",
        signature="update_divide_operations_modtime",
        on_entity="iag.divide_operations",
        is_constraint=False,
        definition="BEFORE UPDATE ON divide_operations\n    FOR EACH ROW EXECUTE FUNCTION iag.update_updated_at_column()",
    )
    op.drop_entity(iag_divide_operations_update_divide_operations_modtime)

    # ### end Alembic commands ###
