"""create extensions and functions

Revision ID: a73ee53acd3a
Revises: 02b2f7a1bf6e
Create Date: 2024-08-07 15:01:24.184555

"""
from typing import Sequence, Union

from alembic import op
from alembic_utils.pg_extension import PGExtension
from alembic_utils.pg_function import PGFunction

# revision identifiers, used by Alembic.
revision: str = "a73ee53acd3a"
down_revision: Union[str, None] = "02b2f7a1bf6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    iag_update_updated_at_column = PGFunction(
        schema="iag",
        signature="update_updated_at_column()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        NEW.updated_at = now();\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql",
    )
    op.create_entity(iag_update_updated_at_column)

    iag_uuid_ossp = PGExtension(schema="iag", signature="uuid-ossp")
    op.create_entity(iag_uuid_ossp)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    iag_uuid_ossp = PGExtension(schema="iag", signature="uuid-ossp")
    op.drop_entity(iag_uuid_ossp)

    iag_update_updated_at_column = PGFunction(
        schema="iag",
        signature="update_updated_at_column()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        NEW.updated_at = now();\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql",
    )
    op.drop_entity(iag_update_updated_at_column)

    # ### end Alembic commands ###
